// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0r5YOnvI8PxAI9A15JecmhVTw7-cE6k',
    appId: '1:770368582809:web:59f2e2613ff41612ab3408',
    messagingSenderId: '770368582809',
    projectId: 'login-createaccount-firebase',
    authDomain: 'login-createaccount-firebase.firebaseapp.com',
    storageBucket: 'login-createaccount-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVGxFtKhbU7k3Zr74fCltcT3X9MmszzU',
    appId: '1:770368582809:android:49794a7a9f98a62fab3408',
    messagingSenderId: '770368582809',
    projectId: 'login-createaccount-firebase',
    storageBucket: 'login-createaccount-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6dyabuRWQwRklRxuSb3JLeYZ4JXRADs',
    appId: '1:770368582809:ios:270a186d79769176ab3408',
    messagingSenderId: '770368582809',
    projectId: 'login-createaccount-firebase',
    storageBucket: 'login-createaccount-firebase.firebasestorage.app',
    iosBundleId: 'com.rancho.studentMarketplace',
  );
}
